name: personal_website
description: "Personal Website of Himanshu Khati (himanshu-khati.vercel.app)"

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  daily_utils: ^0.0.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.2.6
  auto_height_grid_view: ^1.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  flutter_gen_runner: null

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/